# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
#Import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
df = pd.read_csv("/content/data_clustering_inverse.csv")

In [3]:
# Tampilkan 5 baris pertama dengan function head.
df.head(5)

,TransactionAmount,PreviousTransactionDate,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,TransactionDate,AmountCategory,AgeGroup,Target
0,14.09,2023-04-11 16:29:14,Debit,San Diego,ATM,70.0,Doctor,81.0,1.0,5112.21,2024-11-04 8:08:08,1,1,1
1,376.24,2023-06-27 16:44:19,Debit,Houston,ATM,68.0,Doctor,141.0,1.0,13758.91,2024-11-04 8:09:35,0,1,2
2,126.29,2023-07-10 18:16:08,Debit,Mesa,Online,19.0,Student,56.0,1.0,1122.35,2024-11-04 8:07:04,2,2,2
3,184.50,2023-05-05 16:32:11,Debit,Raleigh,Online,26.0,Student,25.0,1.0,8569.06,2024-11-04 8:09:06,2,2,1
4,92.15,2023-04-03 17:15:01,Debit,Oklahoma City,ATM,18.0,Student,172.0,1.0,781.68,2024-11-04 8:06:36,1,2,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TransactionAmount        2398 non-null   float64
 1   PreviousTransactionDate  2370 non-null   object
 2   TransactionType          2398 non-null   object
 3   Location                 2368 non-null   object
 4   Channel                  2372 non-null   object
 5   CustomerAge              2398 non-null   float64
 6   CustomerOccupation       2375 non-null   object
 7   TransactionDuration      2398 non-null   float64
 8   LoginAttempts            2398 non-null   float64
 9   AccountBalance           2398 non-null   float64
 10  TransactionDate          2376 non-null   object
 11  AmountCategory           2398 non-null   int64
 12  AgeGroup                 2398 non-null   int64
 13  Target                   2398 non-null   int64
dtypes: float64(5), int64(3), object(6)
memory usage: 262.4+ KB

In [5]:
# Melakukan feature encoding menggunakan LabelEncoder() untuk fitur kategorikal.
df_encode = df.copy()
label_Encoder = LabelEncoder()
fitur_Encoder = ['PreviousTransactionDate','TransactionType','Location','Channel','CustomerOccupation','TransactionDate']
for col in fitur_Encoder:
    df_encode[col]=label_Encoder.fit_transform(df_encode[col])
df_encode.head()

,TransactionAmount,PreviousTransactionDate,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,TransactionDate,AmountCategory,AgeGroup,Target
0,14.09,649,0,36,0,70.0,0,81.0,1.0,5112.21,105,1,1,1
1,376.24,1126,0,15,0,68.0,0,141.0,1.0,13758.91,192,0,1,2
2,126.29,1206,0,23,2,19.0,3,56.0,1.0,1122.35,41,2,2,2
3,184.50,783,0,33,2,26.0,3,25.0,1.0,8569.06,163,2,2,1
4,92.15,607,0,28,0,18.0,3,172.0,1.0,781.68,13,1,2,1

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [6]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
X = df_encode.drop(["Target"], axis = 1)
y = df_encode["Target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [7]:
# Buatlah model klasifikasi menggunakan Decision Tree
dt = DecisionTreeClassifier()
dt = dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)

In [8]:
# Menyimpan Model
import joblib
joblib.dump(dt, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**

**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [9]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree.
knn = KNeighborsClassifier (n_neighbors=9)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

In [10]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.
#Hasil evaluasi algoritma Decision Tree
precision_dt = precision_score(y_test, y_pred, average = 'macro')
recall_dt = recall_score(y_test, y_pred, average = 'macro')
f1_dt =f1_score(y_test, y_pred, average = 'macro')
akurasi_dt = accuracy_score(y_test, y_pred)

#Hasil evaluasi algoritma KNN
precision_knn = precision_score(y_test, y_pred_knn, average = 'macro')
recall_knn = recall_score(y_test, y_pred_knn, average = 'macro')
f1_knn =f1_score(y_test, y_pred_knn, average = 'macro')
akurasi_knn = accuracy_score(y_test, y_pred_knn)

print('Hasil Evaluasi Algoritma Decision Tree :')
print('- Accuracy:{:.4f}'.format(akurasi_dt))
print('- Precision:{:.4f}'.format(precision_dt))
print('- Recall:{:.4f}'.format(recall_dt))
print('- F1 Score:{:.4f}''\n'.format(f1_dt))

print('Hasil Evaluasi Algoritma KNN Classifier :')
print('- Accuracy:{:.4f}'.format(akurasi_knn))
print('- Precision:{:.4f}'.format(precision_knn))
print('- Recall:{:.4f}'.format(recall_knn))
print('- F1 Score:{:.4f}'.format(f1_knn))

Hasil Evaluasi Algoritma Decision Tree :
- Accuracy:0.9979
- Precision:0.9979
- Recall:0.9979
- F1 Score:0.9979

Hasil Evaluasi Algoritma KNN Classifier :
- Accuracy:0.9521
- Precision:0.9522
- Recall:0.9512
- F1 Score:0.9511

In [11]:
# Menyimpan Model Selain Decision Tree
import joblib
joblib.dump(knn, 'explore_knn_classification.h5')

['explore_knn_classification.h5']

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [12]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.
param_grid = {
    'n_neighbors': list(range(1,31)),
    'weights': ['uniform', 'distance'],
    'metric': ['minkowski','euclidean', 'manhattan']
}

knn_grid = KNeighborsClassifier()
grid_search = GridSearchCV(estimator=knn_grid, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)
best_knn = grid_search.best_estimator_
y_pred_knn_grid = best_knn.predict(X_test)

# Melihat parameter terbaik dari hasil Grid Search
print(f'- Best Params: {grid_search.best_params_}')

- Best Params: {'metric': 'manhattan', 'n_neighbors': 28, 'weights': 'distance'}

In [13]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.
precision_knn_grid = precision_score(y_test, y_pred_knn_grid, average = 'macro')
recall_knn_grid = recall_score(y_test, y_pred_knn_grid, average = 'macro')
f1_knn_grid =f1_score(y_test, y_pred_knn_grid, average = 'macro')
akurasi_knn_grid = accuracy_score(y_test, y_pred_knn_grid)

print('Hasil Evaluasi Algoritma KNN Classifier :')
print('- Accuracy:{:.4f}'.format(akurasi_knn_grid))
print('- Precision:{:.4f}'.format(precision_knn_grid))
print('- Recall:{:.4f}'.format(recall_knn_grid))
print('- F1 Score:{:.4f}'.format(f1_knn_grid))

Hasil Evaluasi Algoritma KNN Classifier :
- Accuracy:0.9625
- Precision:0.9631
- Recall:0.9617
- F1 Score:0.9617

In [14]:
# Menyimpan Model hasil tuning
import joblib
joblib.dump(knn_grid, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code